apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cyberchef
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'github.com/matjahs/synology-k3s'
    targetRevision: HEAD
    path: cluster-gitops/platform/cyberchef
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
