apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: guacamole-db-app
  namespace: tools
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: guacamole-db-app
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: guacamole/db
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: guacamole-oidc-secret
  namespace: tools
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: guacamole-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: guacamole/oidc
        property: client-secret
