apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tools

resources:
  - external-secret.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - initdb-configmap.yaml
  - db-init-job.yaml
