apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cyberchef
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/matjahs/synology-k3s.git
    targetRevision: HEAD
    path: apps/cyberchef
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
