apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-app
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: keycloak-db-app
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: keycloak/db
        property: username
    - secretKey: password
      remoteRef:
        key: keycloak/db
        property: password
