apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backup-s3
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: cnpg-backup-s3
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: cnpg/backup-s3
        property: access_key_id
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: cnpg/backup-s3
        property: secret_access_key
    - secretKey: REGION
      remoteRef:
        key: cnpg/backup-s3
        property: region
    - secretKey: ENDPOINT_URL
      remoteRef:
        key: cnpg/backup-s3
        property: endpoint_url
    - secretKey: BUCKET
      remoteRef:
        key: cnpg/backup-s3
        property: bucket
