apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: keycloak-db-daily
  namespace: keycloak
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: keycloak-db
  immediate: true
