apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-user: admin
        admin-password: "{{ .admin-password }}"
  data:
    - secretKey: admin-password
      remoteRef:
        key: grafana/admin
        property: password
