apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: splunk-otel-collector
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: splunk-otel-collector
    creationPolicy: Owner
  data:
    - secretKey: splunk_observability_access_token
      remoteRef:
        key: splunk-otel-collector/observability-cloud
        property: access-token
