apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splunk-otel-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://signalfx.github.io/splunk-otel-collector-chart
    chart: splunk-otel-collector
    targetRevision: 0.154.0
    helm:
      values: |
        clusterName: synology-k3s

        splunkObservability:
          realm: eu1
          ingestUrl: https://ingest.eu1.signalfx.com
          apiUrl: https://api.eu1.signalfx.com

        secret:
          create: false
          name: splunk-otel-collector

        agent:
          enabled: true

        clusterReceiver:
          enabled: true

        logsCollection:
          enabled: true

        gateway:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
