apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: "https://vault.mxe11.nl:8200"
      path: "secret"
      version: "v2"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZuVENDQTRXZ0F3SUJBZ0lUVndBQUFFQ3hCYlpDTGN6TWN3QUNBQUFBUURBTkJna3Foa2lHOXcwQkFRc0YKQURCWU1SSXdFQVlLQ1pJbWlaUHlMR1FCR1JZQ2Jtd3hGVEFUQmdvSmtpYUprL0lzWkFFWkZnVnRlR1V4TVRFVQpNQklHQ2dtU0pvbVQ4aXhrQVJrV0JHTnZjbkF4RlRBVEJnTlZCQU1UREVOUFVsQWdVbTl2ZENCRFFUQWVGdzB5Ck5qQTJNVEl4TmpRM01UWmFGdzB5T0RBMk1USXhOalUzTVRaYU1EQXhFREFPQmdOVkJBc1RCMGh2YldWc1lXSXgKSERBYUJnTlZCQU1URTFaaGRXeDBJRWx6YzNWcGJtY2dRMEVnUnpFd2dnR2lNQTBHQ1NxR1NJYjNEUUVCQVFVQQpBNElCandBd2dnR0tBb0lCZ1FEclYvK1hudHRjL0JwditySjBUcUtORFZLcGxJUFRKZUZaS0gyam9lOUJRK0lLCjFBcVVzYThWUVVzc2JqMVkwSUFtSG5mQ3doMm5iYkx2d0wrcDlwREJQYlZTWHRyWloyTXlMeG9hTFltbTl2ZnIKQXVSRjRVdU8ybmVWS3BMMUJiNGNsQ2N3OXUyeUswSHZKQ2tzaTNRQlF4S0RrRXJyOTNLMS9sQzFDanVxYVowVgp6WnVGMFJucC9JcjN1c1UvclJiWmRKd3QrN2VTbFhzWGlCM1JkSEdweFliendOeG5lMWwxUExzdnVkYjQ3Vmd4CjZiZWhRWUl2U2Jsb1FxY0ViclpFTldJYVFSUURTajd5b3hMZHNBMTNqaWtGQW5aL1pkY21GVFV1bWJhZ2pZUXkKeFE4OHBOUSszeEJiQ3FrZ1F1TlgvczZ1YW9SUGcwSmMwV0pUSW9IK2EzOUFLakRxRmNiQy9RQlhZVnhnM1hQQgpLQUtYa1NFclJyZm5CTmN6d1ZHd0IrVURGbFZDWlltVEhNNksybWFHMWw4MCtya2FJc0wwUXljMUhJT0tFWVhrCng2bGp6dWNOby81MkhYak91ZVdEQkhEbVN1WXFYWGpqdS9EL1F1VUV6NWx4YTlQRjlqWGxsZEppVndLY3FwTkwKTzV1ZTQraVR4dUh3M2xRb0tMRUNBd0VBQWFPQ0FRWXdnZ0VDTUIwR0ExVWREZ1FXQkJRSlBneC9LUFM0Z2xHTApxMGh2Qmo1TU5ORmcyREFmQmdOVkhTTUVHREFXZ0JSKytNYnZud3lwek5rWm1rdlVYZVhGVmdCN1dEQTlCZ05WCkhSOEVOakEwTURLZ01LQXVoaXhvZEhSd09pOHZjR3RwTG1OdmNuQXViWGhsTVRFdWJtd3ZRMDlTVUMxU2IyOTAKTFVOQktESXBMbU55YkRCRkJnZ3JCZ0VGQlFjQkFRUTVNRGN3TlFZSUt3WUJCUVVITUFLR0tXaDBkSEE2THk5dwphMmt1WTI5eWNDNXRlR1V4TVM1dWJDOURUMUpRTFZKdmIzUXRRMEV1WTNKME1Ca0dDU3NHQVFRQmdqY1VBZ1FNCkhnb0FVd0IxQUdJQVF3QkJNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHR01BMEcKQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUJzYTZuYlpiaTFOS3ZnYTJmZVNjY0R2WTI1Y1c3L3VhTkJVaXNMbGJ1TAp6REIvaGhTclBqMFBVT0FIUTRiUm9lUnZ2S0h0aDNmMTdrTkFTRTJUY2I4STdvZTRqaTJOc2Q1L0xSSnZDbTVCCkVsY3o1YTNlVStONHN2OWdtYkJxVWZjUkZxenVRcURVdzhTMkdEVlBxakx2MzdvUkt3Yks2VEVPTE0yRUlOeWQKdURiekVRVGVIY0h5cmhWS2QxaTlSUE4vc3V6RGdwdjRzSHNMNENvNmR0ZVFYdElQWlJJRXhmd3NKSG14N3o5Sgo0Nzl1SnNVcGJLY2psM0l4Kzhld2JKWWx2MmJyTitIazNsbkVPN2xPdTdBbDJlQU82N1B0VXZoRE53QnVEL3g0ClhWaEtYU21JVkVybnNxVmc4RjVTVktUaG1MeE1rQTQ5UENtcGdHSUIrOCtEZnVaVHlzQ1Z1cXJjK21TQXlzTVAKUlUrRWo4akpIZnlJYVpuMVhTeElDaGxXV2ppTjIvLzZMRExoYkI5RjcvOTBBTzlQN2tLVEpQamJSN01sS1c1TgpNaDJZMFFnMDhVRmo0OTNiNHlHMFBlUWtuN2dEK3hScmpnVXMxVkdpMUtLeEE5ZDRqSGRHaVBRWmJuL3dmVFlECnAzemJoN1JacU5pL2tiQTlMR2tDcEhDOHVrOGdlaGh4aDBGVTBhZHlkK2lONHhvWjRTUVFPaFlCenArWUFrTEcKTUdzcllEZlgzaTd3OC9uNlJjU0xLTTJOWDVOQS9udTkvTUxiZ0lZKzA2R3pld0l6NytuSnNwYitEY1JqYlF3VgpScHlzTWlUMzNyWnlDRCtpTFl0aDEvVUdJMUJWTmxUZkN4NjF1UnNOSi94L3VCNnZOR3FOeVpXNDVPd3ZoaTF0Ci9nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"
