apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-db-app
  namespace: netbox
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: netbox-db-app
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: netbox/db
        property: username
    - secretKey: password
      remoteRef:
        key: netbox/db
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-secrets
  namespace: netbox
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: netbox-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .secret_key }}"
        SUPERUSER_NAME: "{{ .superuser_name }}"
        SUPERUSER_EMAIL: "{{ .superuser_email }}"
        SUPERUSER_PASSWORD: "{{ .superuser_password }}"
        DB_USER: "{{ .username }}"
        DB_PASSWORD: "{{ .password }}"
  data:
    - secretKey: secret_key
      remoteRef:
        key: netbox/app
        property: secret_key
    - secretKey: superuser_name
      remoteRef:
        key: netbox/app
        property: superuser_name
    - secretKey: superuser_email
      remoteRef:
        key: netbox/app
        property: superuser_email
    - secretKey: superuser_password
      remoteRef:
        key: netbox/app
        property: superuser_password
    - secretKey: username
      remoteRef:
        key: netbox/db
        property: username
    - secretKey: password
      remoteRef:
        key: netbox/db
        property: password
