apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: netbox-db
  namespace: netbox
spec:
  instances: 1

  storage:
    size: 4Gi
    storageClass: synology-iscsi

  bootstrap:
    initdb:
      database: netbox
      owner: netbox
      secret:
        name: netbox-db-app
