apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-image-updater-nexus-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: argocd-image-updater-nexus-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {{- $auth := printf "%s:%s" .username .password | b64enc }}
          {{- printf "{\"auths\":{\"nexus.lab.mxe11.nl\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .username .password $auth }}
  data:
    - secretKey: username
      remoteRef:
        key: backstage/nexus-docker
        property: username
    - secretKey: password
      remoteRef:
        key: backstage/nexus-docker
        property: password
