apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-image-updater-git-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: argocd-image-updater-git-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        githubAppID: "{{ .app_id }}"
        githubAppInstallationID: "{{ .installation_id }}"
        githubAppPrivateKey: "{{ .private_key }}"
  data:
    - secretKey: app_id
      remoteRef:
        key: argocd/git
        property: app_id
    - secretKey: installation_id
      remoteRef:
        key: argocd/git
        property: installation_id
    - secretKey: private_key
      remoteRef:
        key: argocd/git
        property: private_key
