apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  namespace: tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi
  resources:
    requests:
      storage: 50Gi
