apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secrets
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: postgres-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: "{{ .username }}"
        POSTGRES_PASSWORD: "{{ .password }}"
        POSTGRES_DB: backstage
  data:
    - secretKey: username
      remoteRef:
        key: backstage/db
        property: username
    - secretKey: password
      remoteRef:
        key: backstage/db
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-secrets
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: backstage-secrets
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: backstage/github
        property: token
    - secretKey: AUTH_KEYCLOAK_CLIENT_SECRET
      remoteRef:
        key: backstage/keycloak
        property: client_secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-docker-creds
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: nexus-docker-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {{- $auth := printf "%s:%s" .username .password | b64enc }}
          {{- printf "{\"auths\":{\"nexus.lab.mxe11.nl\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .username .password $auth }}
  data:
    - secretKey: username
      remoteRef:
        key: backstage/nexus-docker
        property: username
    - secretKey: password
      remoteRef:
        key: backstage/nexus-docker
        property: password
