apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage

resources:
  - postgres-storage.yaml
  - postgres.yaml
  - postgres-service.yaml
  - kubernetes-rbac.yaml
  - backstage.yaml
  - backstage-service.yaml
  - httproute.yaml
  - external-secret.yaml

images:
  - name: nexus.lab.mxe11.nl/backstage/backstage
    newTag: "1.1.4"
